const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const LOCALES_DIR = path.join(ROOT, "src/l10n/locales");
const EN_PATH = path.join(LOCALES_DIR, "en.ts");
const CATALOG_PATH = path.join(__dirname, "locale-catalog.json");

/** Must match src/l10n/bundled.ts. English is maintained separately in en.ts. */
const BUNDLED_LOCALE_CODES = [
  "zh",
  "zh-TW",
  "ja",
  "ko",
  "de",
  "fr",
  "es",
  "ru",
  "pt-BR",
  "it",
];

function readInputs() {
  const englishSource = fs.readFileSync(EN_PATH, "utf8");
  const translationKeys = [...englishSource.matchAll(/^\s+(\w+):/gm)].map(
    (match) => match[1],
  );
  if (translationKeys.length === 0 || new Set(translationKeys).size !== translationKeys.length) {
    throw new Error("Could not derive a unique translation-key list from src/l10n/locales/en.ts");
  }

  const catalog = JSON.parse(fs.readFileSync(CATALOG_PATH, "utf8"));
  const catalogCodes = Object.keys(catalog).sort((a, b) => a.localeCompare(b));
  const lazyCodes = catalogCodes.filter((code) => !BUNDLED_LOCALE_CODES.includes(code));
  return { catalog, catalogCodes, englishSource, lazyCodes, translationKeys };
}

function validateCatalog(catalog, catalogCodes, translationKeys) {
  const errors = [];
  const expectedKeys = new Set(translationKeys);

  for (const code of BUNDLED_LOCALE_CODES) {
    if (!(code in catalog)) errors.push(`catalog is missing bundled locale ${code}`);
  }

  for (const code of catalogCodes) {
    const strings = catalog[code];
    if (!strings || typeof strings !== "object" || Array.isArray(strings)) {
      errors.push(`${code} must contain a translation object`);
      continue;
    }

    const actualKeys = Object.keys(strings);
    const missing = translationKeys.filter((key) => !(key in strings));
    const unexpected = actualKeys.filter((key) => !expectedKeys.has(key));
    const invalid = actualKeys.filter((key) => typeof strings[key] !== "string");
    if (missing.length > 0) errors.push(`${code} missing: ${missing.join(", ")}`);
    if (unexpected.length > 0) errors.push(`${code} unexpected: ${unexpected.join(", ")}`);
    if (invalid.length > 0) errors.push(`${code} non-string: ${invalid.join(", ")}`);
  }
  return errors;
}

function renderLocaleFile(strings, translationKeys) {
  const lines = [
    'import type { TranslationKey } from "./en";',
    "",
    "export const locale: Record<TranslationKey, string> = {",
  ];
  for (const key of translationKeys) lines.push(`  ${key}: ${JSON.stringify(strings[key])},`);
  lines.push("};", "");
  return lines.join("\n");
}

function renderBundledIndex() {
  const codes = [...BUNDLED_LOCALE_CODES].sort((a, b) => a.localeCompare(b));
  const imports = codes.map(
    (code) => `import { locale as locale_${safeIdentifier(code)} } from "./${code}";`,
  );
  const entries = codes.map(
    (code) => `  ${JSON.stringify(code)}: locale_${safeIdentifier(code)},`,
  );
  return [
    "/** Generated by scripts/seed-locales.cjs; do not edit by hand. */",
    'import { en } from "./en";',
    'import type { TranslationKey } from "./en";',
    ...imports,
    "",
    "export const bundledLocales: Record<string, Record<TranslationKey, string>> = {",
    "  en,",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function renderBundledCodes() {
  return [
    "/** Generated by scripts/seed-locales.cjs; do not edit by hand. */",
    "/** Shipped inside main.js for zero-latency UI. */",
    "export const BUNDLED_LOCALE_CODES = [",
    ...BUNDLED_LOCALE_CODES.map((code) => `  ${JSON.stringify(code)},`),
    "] as const;",
    "",
    "export type BundledLocaleCode = (typeof BUNDLED_LOCALE_CODES)[number];",
    "",
  ].join("\n");
}

function renderLazyCodes(codes) {
  return [
    "/** Generated by scripts/seed-locales.cjs; do not edit by hand. */",
    "export const LAZY_LOCALE_CODES = [",
    ...codes.map((code) => `  ${JSON.stringify(code)},`),
    "] as const;",
    "",
  ].join("\n");
}

function renderExtras(catalog, codes) {
  return JSON.stringify(Object.fromEntries(codes.map((code) => [code, catalog[code]])));
}

function safeIdentifier(code) {
  return code.replace(/-/g, "_");
}

module.exports = {
  BUNDLED_LOCALE_CODES,
  CATALOG_PATH,
  EN_PATH,
  LOCALES_DIR,
  ROOT,
  readInputs,
  renderBundledCodes,
  renderBundledIndex,
  renderExtras,
  renderLazyCodes,
  renderLocaleFile,
  validateCatalog,
};
