const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");

const ROOT = path.join(__dirname, "..");
const LOCALES_DIR = path.join(ROOT, "src/l10n/locales");
const EN_PATH = path.join(LOCALES_DIR, "en.ts");
const CATALOG_PATH = path.join(__dirname, "locale-catalog.json");

function compareLocaleCodes(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Every catalog locale is embedded in main.js. English is maintained in en.ts. */
const BUNDLED_LOCALE_CODES = Object.keys(
  JSON.parse(fs.readFileSync(CATALOG_PATH, "utf8")),
).sort(compareLocaleCodes);

function readInputs() {
  const englishSource = fs.readFileSync(EN_PATH, "utf8");
  const translationKeys = [...englishSource.matchAll(/^\s+(\w+):/gm)].map(
    (match) => match[1],
  );
  if (translationKeys.length === 0 || new Set(translationKeys).size !== translationKeys.length) {
    throw new Error("Could not derive a unique translation-key list from src/l10n/locales/en.ts");
  }

  const catalog = JSON.parse(fs.readFileSync(CATALOG_PATH, "utf8"));
  const catalogCodes = Object.keys(catalog).sort(compareLocaleCodes);
  return { catalog, catalogCodes, englishSource, translationKeys };
}

function validateCatalog(catalog, catalogCodes, translationKeys) {
  const errors = [];
  const expectedKeys = new Set(translationKeys);

  for (const code of BUNDLED_LOCALE_CODES) {
    if (!(code in catalog)) errors.push(`catalog is missing bundled locale ${code}`);
  }

  for (const code of catalogCodes) {
    const strings = catalog[code];
    if (!strings || typeof strings !== "object" || Array.isArray(strings)) {
      errors.push(`${code} must contain a translation object`);
      continue;
    }

    const actualKeys = Object.keys(strings);
    const missing = translationKeys.filter((key) => !(key in strings));
    const unexpected = actualKeys.filter((key) => !expectedKeys.has(key));
    const invalid = actualKeys.filter((key) => typeof strings[key] !== "string");
    if (missing.length > 0) errors.push(`${code} missing: ${missing.join(", ")}`);
    if (unexpected.length > 0) errors.push(`${code} unexpected: ${unexpected.join(", ")}`);
    if (invalid.length > 0) errors.push(`${code} non-string: ${invalid.join(", ")}`);
  }
  return errors;
}

function renderLocaleFile(strings, translationKeys) {
  const lines = [
    'import type { TranslationKey } from "./en";',
    "",
    "export const locale: Record<TranslationKey, string> = {",
  ];
  for (const key of translationKeys) lines.push(`  ${key}: ${JSON.stringify(strings[key])},`);
  lines.push("};", "");
  return lines.join("\n");
}

function renderBundledIndex(catalog, translationKeys) {
  const codes = [...BUNDLED_LOCALE_CODES].sort(compareLocaleCodes);
  const entries = codes.map(
    (code) =>
      `  ${JSON.stringify(code)}: ${JSON.stringify(compressLocale(catalog[code], translationKeys))},`,
  );
  return [
    "/** Generated by scripts/seed-locales.cjs; do not edit by hand. */",
    'import type { TranslationKey } from "./en";',
    "",
    "export const BUNDLED_LOCALE_KEYS = [",
    ...translationKeys.map((key) => `  ${JSON.stringify(key)},`),
    "] as const satisfies readonly TranslationKey[];",
    "",
    "export const BUNDLED_LOCALE_GZIP_BASE64: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function renderBundledCodes() {
  return [
    "/** Generated by scripts/seed-locales.cjs; do not edit by hand. */",
    "/** Shipped inside main.js for complete offline UI. */",
    "export const BUNDLED_LOCALE_CODES = [",
    ...BUNDLED_LOCALE_CODES.map((code) => `  ${JSON.stringify(code)},`),
    "] as const;",
    "",
    "export type BundledLocaleCode = (typeof BUNDLED_LOCALE_CODES)[number];",
    "",
  ].join("\n");
}

function compressLocale(strings, translationKeys) {
  const values = translationKeys.map((key) => strings[key]);
  const gzip = zlib.gzipSync(Buffer.from(JSON.stringify(values), "utf8"), {
    level: zlib.constants.Z_BEST_COMPRESSION,
  });
  // RFC 1952 byte 9 identifies the generating OS. Normalize it so Windows and
  // Linux produce byte-identical generated locale modules.
  gzip[9] = 255;
  return gzip.toString("base64");
}

module.exports = {
  BUNDLED_LOCALE_CODES,
  CATALOG_PATH,
  EN_PATH,
  LOCALES_DIR,
  ROOT,
  readInputs,
  renderBundledCodes,
  renderBundledIndex,
  renderLocaleFile,
  validateCatalog,
};
