const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const LOCALES_DIR = path.join(ROOT, "src/l10n/locales");
const EN_PATH = path.join(LOCALES_DIR, "en.ts");
const CATALOG_PATH = path.join(__dirname, "locale-catalog.json");
const INDEX_PATH = path.join(LOCALES_DIR, "index.ts");
const LAZY_CODES_PATH = path.join(ROOT, "src/l10n/lazy-codes.ts");
const EXTRAS_PATH = path.join(ROOT, "locales-extras.json");

/** Must match src/l10n/bundled.ts (excluding en, which lives in en.ts). */
const BUNDLED = ["zh", "zh-TW", "ja", "ko", "de", "fr", "es", "ru", "pt-BR", "it"];

const enSource = fs.readFileSync(EN_PATH, "utf8");
const keys = [...enSource.matchAll(/^\s+(\w+):/gm)].map((match) => match[1]);
const catalog = require(CATALOG_PATH);
const catalogCodes = Object.keys(catalog).sort((a, b) => a.localeCompare(b));

function escapeTsString(value) {
  return JSON.stringify(value);
}

function writeLocaleFile(code, strings) {
  const filePath = path.join(LOCALES_DIR, `${code}.ts`);
  const lines = [
    'import type { TranslationKey } from "./en";',
    "",
    "export const locale: Record<TranslationKey, string> = {",
  ];

  for (const key of keys) {
    const value = strings[key];
    if (typeof value !== "string") {
      throw new Error(`Missing key "${key}" for locale "${code}"`);
    }
    lines.push(`  ${key}: ${escapeTsString(value)},`);
  }

  lines.push("};", "");
  fs.writeFileSync(filePath, lines.join("\n"), "utf8");
}

function writeBundledIndex(codes) {
  const sorted = [...codes].sort((a, b) => a.localeCompare(b));
  const imports = sorted.map((code) => `import { locale as locale_${safeId(code)} } from "./${code}";`);
  const entries = sorted.map((code) => `  ${JSON.stringify(code)}: locale_${safeId(code)},`);

  const content = [
    'import { en } from "./en";',
    'import type { TranslationKey } from "./en";',
    ...imports,
    "",
    "export const bundledLocales: Record<string, Record<TranslationKey, string>> = {",
    "  en,",
    ...entries,
    "};",
    "",
  ].join("\n");

  fs.writeFileSync(INDEX_PATH, content, "utf8");
}

function writeLazyCodes(codes) {
  const lines = [
    "/** Generated by scripts/seed-locales.cjs — do not edit by hand. */",
    "export const LAZY_LOCALE_CODES = [",
    ...codes.map((code) => `  ${JSON.stringify(code)},`),
    "] as const;",
    "",
  ];
  fs.writeFileSync(LAZY_CODES_PATH, lines.join("\n"), "utf8");
}

function writeExtras(codes) {
  const extras = {};
  for (const code of codes) {
    extras[code] = catalog[code];
  }
  fs.writeFileSync(EXTRAS_PATH, JSON.stringify(extras), "utf8");
}

function safeId(code) {
  return code.replace(/-/g, "_");
}

function cleanStaleLocaleFiles() {
  const keep = new Set(["en.ts", "index.ts", ...BUNDLED.map((code) => `${code}.ts`)]);
  for (const file of fs.readdirSync(LOCALES_DIR)) {
    if (!file.endsWith(".ts") || keep.has(file)) continue;
    fs.unlinkSync(path.join(LOCALES_DIR, file));
  }
}

if (!fs.existsSync(LOCALES_DIR)) {
  fs.mkdirSync(LOCALES_DIR, { recursive: true });
}

const missingBundled = BUNDLED.filter((code) => !catalog[code]);
if (missingBundled.length > 0) {
  throw new Error(`Missing bundled locales in catalog: ${missingBundled.join(", ")}`);
}

const lazyCodes = catalogCodes.filter((code) => !BUNDLED.includes(code));

cleanStaleLocaleFiles();

for (const code of BUNDLED) {
  writeLocaleFile(code, catalog[code]);
}

writeBundledIndex(BUNDLED);
writeLazyCodes(lazyCodes);
writeExtras(lazyCodes);

console.log(
  `Bundled ${BUNDLED.length} locales (+ en), lazy ${lazyCodes.length} locales in ${path.relative(ROOT, EXTRAS_PATH)}.`,
);
